inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - test/**/*
    - spec/**/*
Style/FormatStringToken:
  Enabled: false
