inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

# This repo does not use ActiveRecord
Rails/SkipsModelValidations:
  Enabled: false

# This repo does not use ActiveRecord
Rails/ActiveRecordAliases:
  Enabled: false
